services:
  portfolio:
    build:
      context: .
      args:
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}"
    container_name: portfolio
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/run/config/with-docker-secrets.sh"]
    command: ["node","server.js"]
    environment:
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}"
      NEXTAUTH_URL: https://brentweb.eu
      UPLOAD_DIR: ./public/uploads
      SECRET_ENV_MAPPINGS: NEXTAUTH_SECRET=/run/secrets/nextauth_secret,JWT_SECRET=/run/secrets/jwt_secret,DATABASE_URL=/run/secrets/database_url
    volumes:
      - ../docker-tools/with-docker-secrets.sh:/run/config/with-docker-secrets.sh:ro
      - ./secrets/nextauth_secret:/run/secrets/nextauth_secret:ro
      - ./secrets/jwt_secret:/run/secrets/jwt_secret:ro
      - ./secrets/database_url:/run/secrets/database_url:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.brentweb.rule=Host(`brentweb.eu`) || Host(`www.brentweb.eu`)"
      - "traefik.http.routers.brentweb.entrypoints=websecure"
      - "traefik.http.routers.brentweb.tls=true"
      - "traefik.http.routers.brentweb.tls.certresolver=letsencrypt"
      - "traefik.http.services.brentweb.loadbalancer.server.port=3000"
    networks:
      - proxy

networks:
  proxy:
    external: true

secrets:
  nextauth_secret:
    file: ./secrets/nextauth_secret
  jwt_secret:
    file: ./secrets/jwt_secret
  database_url:
    file: ./secrets/database_url
